spring:
  rabbitmq:
    host: 192.168.13.13
    username: admin
    password: 123456
    virtual-host: /
    # 消费端配置
    listener:
      simple:
        concurrency: 5
        # 手动ack
        acknowledge-mode: manual
        max-concurrency: 10
        # 预处理消息数
        prefetch: 5

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.13.13:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Fishball95@
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 9999
  servlet:
    context-path: /
